/* tslint:disable */
/* eslint-disable */
/**
 * CLOUD API
 * IONOS Enterprise-grade Infrastructure as a Service (IaaS) solutions can be managed through the Cloud API, in addition or as an alternative to the \"Data Center Designer\" (DCD) browser-based tool.    Both methods employ consistent concepts and features, deliver similar power and flexibility, and can be used to perform a multitude of management tasks, including adding servers, volumes, configuring networks, and so on.
 *
 * The version of the OpenAPI document: 6.0-SDK.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FlowLogProperties
 */
export interface FlowLogProperties {
    /**
     * A name of that resource
     * @type {string}
     * @memberof FlowLogProperties
     */
    name: string;
    /**
     * Specifies the traffic action pattern.
     * @type {string}
     * @memberof FlowLogProperties
     */
    action: FlowLogPropertiesActionEnum;
    /**
     * Specifies the traffic direction pattern.
     * @type {string}
     * @memberof FlowLogProperties
     */
    direction: FlowLogPropertiesDirectionEnum;
    /**
     * S3 bucket name of an existing IONOS Cloud S3 bucket.
     * @type {string}
     * @memberof FlowLogProperties
     */
    bucket: string;
}

/**
    * @export
    * @enum {string}
    */
export enum FlowLogPropertiesActionEnum {
    Accepted = 'ACCEPTED',
    Rejected = 'REJECTED',
    All = 'ALL'
}
/**
    * @export
    * @enum {string}
    */
export enum FlowLogPropertiesDirectionEnum {
    Ingress = 'INGRESS',
    Egress = 'EGRESS',
    Bidirectional = 'BIDIRECTIONAL'
}



