/* tslint:disable */
/* eslint-disable */
/**
 * CLOUD API
 * IONOS Enterprise-grade Infrastructure as a Service (IaaS) solutions can be managed through the Cloud API, in addition or as an alternative to the \"Data Center Designer\" (DCD) browser-based tool.    Both methods employ consistent concepts and features, deliver similar power and flexibility, and can be used to perform a multitude of management tasks, including adding servers, volumes, configuring networks, and so on.
 *
 * The version of the OpenAPI document: 6.0-SDK.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GroupProperties
 */
export interface GroupProperties {
    /**
     * A name of that resource
     * @type {string}
     * @memberof GroupProperties
     */
    name?: string;
    /**
     * create data center privilege
     * @type {boolean}
     * @memberof GroupProperties
     */
    createDataCenter?: boolean;
    /**
     * create snapshot privilege
     * @type {boolean}
     * @memberof GroupProperties
     */
    createSnapshot?: boolean;
    /**
     * reserve ip block privilege
     * @type {boolean}
     * @memberof GroupProperties
     */
    reserveIp?: boolean;
    /**
     * activity log access privilege
     * @type {boolean}
     * @memberof GroupProperties
     */
    accessActivityLog?: boolean;
    /**
     * create pcc privilege
     * @type {boolean}
     * @memberof GroupProperties
     */
    createPcc?: boolean;
    /**
     * S3 privilege
     * @type {boolean}
     * @memberof GroupProperties
     */
    s3Privilege?: boolean;
    /**
     * create backup unit privilege
     * @type {boolean}
     * @memberof GroupProperties
     */
    createBackupUnit?: boolean;
    /**
     * create internet access privilege
     * @type {boolean}
     * @memberof GroupProperties
     */
    createInternetAccess?: boolean;
    /**
     * create kubernetes cluster privilege
     * @type {boolean}
     * @memberof GroupProperties
     */
    createK8sCluster?: boolean;
    /**
     * create Flow Logs privilege
     * @type {boolean}
     * @memberof GroupProperties
     */
    createFlowLog?: boolean;
    /**
     * Privilege for a group to access and manage monitoring related functionality (access metrics, CRUD on alarms, alarm-actions etc) using Monotoring-as-a-Service (MaaS).
     * @type {boolean}
     * @memberof GroupProperties
     */
    accessAndManageMonitoring?: boolean;
    /**
     * Privilege for a group to access and manage certificates.
     * @type {boolean}
     * @memberof GroupProperties
     */
    accessAndManageCertificates?: boolean;
}


