/* tslint:disable */
/* eslint-disable */
/**
 * CLOUD API
 * IONOS Enterprise-grade Infrastructure as a Service (IaaS) solutions can be managed through the Cloud API, in addition or as an alternative to the \"Data Center Designer\" (DCD) browser-based tool.    Both methods employ consistent concepts and features, deliver similar power and flexibility, and can be used to perform a multitude of management tasks, including adding servers, volumes, configuring networks, and so on.
 *
 * The version of the OpenAPI document: 6.0-SDK.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { KubernetesCluster } from './kubernetes-cluster';

/**
 * 
 * @export
 * @interface KubernetesClusters
 */
export interface KubernetesClusters {
    /**
     * Unique representation for Kubernetes Cluster as a collection on a resource.
     * @type {string}
     * @memberof KubernetesClusters
     */
    id?: string;
    /**
     * The type of resource within a collection
     * @type {string}
     * @memberof KubernetesClusters
     */
    type?: KubernetesClustersTypeEnum;
    /**
     * URL to the collection representation (absolute path)
     * @type {string}
     * @memberof KubernetesClusters
     */
    href?: string;
    /**
     * Array of items in that collection
     * @type {Array<KubernetesCluster>}
     * @memberof KubernetesClusters
     */
    items?: Array<KubernetesCluster>;
}

/**
    * @export
    * @enum {string}
    */
export enum KubernetesClustersTypeEnum {
    Collection = 'collection'
}



