/* tslint:disable */
/* eslint-disable */
/**
 * CLOUD API
 *  IONOS Enterprise-grade Infrastructure as a Service (IaaS) solutions can be managed through the Cloud API, in addition or as an alternative to the \"Data Center Designer\" (DCD) browser-based tool.    Both methods employ consistent concepts and features, deliver similar power and flexibility, and can be used to perform a multitude of management tasks, including adding servers, volumes, configuring networks, and so on.
 *
 * The version of the OpenAPI document: 6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { LabelResourceProperties } from './label-resource-properties';
import { NoStateMetaData } from './no-state-meta-data';

/**
 * 
 * @export
 * @interface LabelResource
 */
export interface LabelResource {

    /**
     * Label on a resource is identified using label key.
     * @type {string}
     * @memberof LabelResource
     */
    id?: string;

    /**
     * The type of object that has been created.
     * @type {string}
     * @memberof LabelResource
     */
    type?: LabelResourceTypeEnum;

    /**
     * URL to the object representation (absolute path).
     * @type {string}
     * @memberof LabelResource
     */
    href?: string;

    /**
     * 
     * @type {NoStateMetaData}
     * @memberof LabelResource
     */
    metadata?: NoStateMetaData;

    /**
     * 
     * @type {LabelResourceProperties}
     * @memberof LabelResource
     */
    properties: LabelResourceProperties;
}



/**
    * @export
    * @enum {string}
    */
export enum LabelResourceTypeEnum {
    Label = 'label'
}






