/* tslint:disable */
/* eslint-disable */
/**
 * CLOUD API
 * IONOS Enterprise-grade Infrastructure as a Service (IaaS) solutions can be managed through the Cloud API, in addition or as an alternative to the \"Data Center Designer\" (DCD) browser-based tool.    Both methods employ consistent concepts and features, deliver similar power and flexibility, and can be used to perform a multitude of management tasks, including adding servers, volumes, configuring networks, and so on.
 *
 * The version of the OpenAPI document: 6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NetworkLoadBalancerForwardingRuleTargetHealthCheck
 */
export interface NetworkLoadBalancerForwardingRuleTargetHealthCheck {

    /**
     * Check specifies whether the target VM\'s health is checked. If turned off, a target VM is always considered available. If turned on, the target VM is available when accepting periodic TCP connections, to ensure that it is really able to serve requests. The address and port to send the tests to are those of the target VM. The health check only consists of a connection attempt.
     * @type {boolean}
     * @memberof NetworkLoadBalancerForwardingRuleTargetHealthCheck
     */
    check?: boolean;

    /**
     * CheckInterval determines the duration (in milliseconds) between consecutive health checks. If unspecified a default of 2000 ms is used.
     * @type {number}
     * @memberof NetworkLoadBalancerForwardingRuleTargetHealthCheck
     */
    checkInterval?: number;

    /**
     * Maintenance specifies if a target VM should be marked as down, even if it is not.
     * @type {boolean}
     * @memberof NetworkLoadBalancerForwardingRuleTargetHealthCheck
     */
    maintenance?: boolean;
}


