/* tslint:disable */
/* eslint-disable */
/**
 * CLOUD API
 * IONOS Enterprise-grade Infrastructure as a Service (IaaS) solutions can be managed through the Cloud API, in addition or as an alternative to the \"Data Center Designer\" (DCD) browser-based tool.    Both methods employ consistent concepts and features, deliver similar power and flexibility, and can be used to perform a multitude of management tasks, including adding servers, volumes, configuring networks, and so on.
 *
 * The version of the OpenAPI document: 6.0-SDK.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NetworkLoadBalancerForwardingRuleTargetHealthCheck } from './network-load-balancer-forwarding-rule-target-health-check';

/**
 * 
 * @export
 * @interface NetworkLoadBalancerForwardingRuleTarget
 */
export interface NetworkLoadBalancerForwardingRuleTarget {
    /**
     * IP of a balanced target VM
     * @type {string}
     * @memberof NetworkLoadBalancerForwardingRuleTarget
     */
    ip: string;
    /**
     * Port of the balanced target service. (range: 1 to 65535)
     * @type {number}
     * @memberof NetworkLoadBalancerForwardingRuleTarget
     */
    port: number;
    /**
     * Weight parameter is used to adjust the target VM\'s weight relative to other target VMs. All target VMs will receive a load proportional to their weight relative to the sum of all weights, so the higher the weight, the higher the load. The default weight is 1, and the maximal value is 256. A value of 0 means the target VM will not participate in load-balancing but will still accept persistent connections. If this parameter is used to distribute the load according to target VM\'s capacity, it is recommended to start with values which can both grow and shrink, for instance between 10 and 100 to leave enough room above and below for later adjustments.
     * @type {number}
     * @memberof NetworkLoadBalancerForwardingRuleTarget
     */
    weight: number;
    /**
     * 
     * @type {NetworkLoadBalancerForwardingRuleTargetHealthCheck}
     * @memberof NetworkLoadBalancerForwardingRuleTarget
     */
    healthCheck?: NetworkLoadBalancerForwardingRuleTargetHealthCheck;
}


