/**
 * CLOUD API
 * An enterprise-grade Infrastructure is provided as a Service (IaaS) solution that can be managed through a browser-based \"Data Center Designer\" (DCD) tool or via an easy to use API.   The API allows you to perform a variety of management tasks such as spinning up additional servers, adding volumes, adjusting networking, and so forth. It is designed to allow users to leverage the same power and flexibility found within the DCD visual tool. Both tools are consistent with their concepts and lend well to making the experience smooth and intuitive.
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class NicProperties {
    /**
    * A name of that resource
    */
    'name'?: string;
    /**
    * The MAC address of the NIC
    */
    'mac'?: string;
    /**
    * Collection of IP addresses assigned to a nic. Explicitly assigned public IPs need to come from reserved IP blocks, Passing value null or empty array will assign an IP address automatically.
    */
    'ips'?: Array<string>;
    /**
    * Indicates if the nic will reserve an IP using DHCP
    */
    'dhcp'?: boolean;
    /**
    * The LAN ID the NIC will sit on. If the LAN ID does not exist it will be implicitly created
    */
    'lan': number;
    /**
    * Activate or deactivate the firewall. By default an active firewall without any defined rules will block all incoming network traffic except for the firewall rules that explicitly allows certain protocols, ip addresses and ports.
    */
    'firewallActive'?: boolean;
    /**
    * Indicates if NAT is enabled on this NIC. This is now deprecated.
    */
    'nat'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "mac",
            "baseName": "mac",
            "type": "string"
        },
        {
            "name": "ips",
            "baseName": "ips",
            "type": "Array<string>"
        },
        {
            "name": "dhcp",
            "baseName": "dhcp",
            "type": "boolean"
        },
        {
            "name": "lan",
            "baseName": "lan",
            "type": "number"
        },
        {
            "name": "firewallActive",
            "baseName": "firewallActive",
            "type": "boolean"
        },
        {
            "name": "nat",
            "baseName": "nat",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return NicProperties.attributeTypeMap;
    }
}

