/* tslint:disable */
/* eslint-disable */
/**
 * CLOUD API
 * IONOS Enterprise-grade Infrastructure as a Service (IaaS) solutions can be managed through the Cloud API, in addition or as an alternative to the \"Data Center Designer\" (DCD) browser-based tool.    Both methods employ consistent concepts and features, deliver similar power and flexibility, and can be used to perform a multitude of management tasks, including adding servers, volumes, configuring networks, and so on.
 *
 * The version of the OpenAPI document: 6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ResourceLimits
 */
export interface ResourceLimits {

    /**
     * The maximum number of cores per server.
     * @type {number}
     * @memberof ResourceLimits
     */
    coresPerServer: number;

    /**
     * The maximum number of cores per contract.
     * @type {number}
     * @memberof ResourceLimits
     */
    coresPerContract: number;

    /**
     * The number of cores provisioned.
     * @type {number}
     * @memberof ResourceLimits
     */
    coresProvisioned: number;

    /**
     * The maximum RAM per server.
     * @type {number}
     * @memberof ResourceLimits
     */
    ramPerServer: number;

    /**
     * The maximum RAM per contract.
     * @type {number}
     * @memberof ResourceLimits
     */
    ramPerContract: number;

    /**
     * RAM provisioned.
     * @type {number}
     * @memberof ResourceLimits
     */
    ramProvisioned: number;

    /**
     * HDD limit per volume.
     * @type {number}
     * @memberof ResourceLimits
     */
    hddLimitPerVolume: number;

    /**
     * HDD limit per contract.
     * @type {number}
     * @memberof ResourceLimits
     */
    hddLimitPerContract: number;

    /**
     * HDD volume provisioned.
     * @type {number}
     * @memberof ResourceLimits
     */
    hddVolumeProvisioned: number;

    /**
     * SSD limit per volume.
     * @type {number}
     * @memberof ResourceLimits
     */
    ssdLimitPerVolume: number;

    /**
     * SSD limit per contract.
     * @type {number}
     * @memberof ResourceLimits
     */
    ssdLimitPerContract: number;

    /**
     * SSD volume provisioned.
     * @type {number}
     * @memberof ResourceLimits
     */
    ssdVolumeProvisioned: number;

    /**
     * DAS (Direct Attached Storage) volume provisioned.
     * @type {number}
     * @memberof ResourceLimits
     */
    dasVolumeProvisioned: number;

    /**
     * Total reservable IP limit for the customer.
     * @type {number}
     * @memberof ResourceLimits
     */
    reservableIps: number;

    /**
     * Reserved ips for the contract.
     * @type {number}
     * @memberof ResourceLimits
     */
    reservedIpsOnContract: number;

    /**
     * Reserved ips in use.
     * @type {number}
     * @memberof ResourceLimits
     */
    reservedIpsInUse: number;

    /**
     * K8s clusters total limit.
     * @type {number}
     * @memberof ResourceLimits
     */
    k8sClusterLimitTotal: number;

    /**
     * K8s clusters provisioned.
     * @type {number}
     * @memberof ResourceLimits
     */
    k8sClustersProvisioned: number;

    /**
     * NLB total limit.
     * @type {number}
     * @memberof ResourceLimits
     */
    nlbLimitTotal: number;

    /**
     * NLBs provisioned.
     * @type {number}
     * @memberof ResourceLimits
     */
    nlbProvisioned: number;

    /**
     * NAT Gateway total limit.
     * @type {number}
     * @memberof ResourceLimits
     */
    natGatewayLimitTotal: number;

    /**
     * NAT Gateways provisioned.
     * @type {number}
     * @memberof ResourceLimits
     */
    natGatewayProvisioned: number;
}


