/* tslint:disable */
/* eslint-disable */
/**
 * CLOUD API
 * IONOS Enterprise-grade Infrastructure as a Service (IaaS) solutions can be managed through the Cloud API, in addition or as an alternative to the \"Data Center Designer\" (DCD) browser-based tool.    Both methods employ consistent concepts and features, deliver similar power and flexibility, and can be used to perform a multitude of management tasks, including adding servers, volumes, configuring networks, and so on.
 *
 * The version of the OpenAPI document: 6.0-SDK.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ResourceLimits
 */
export interface ResourceLimits {
    /**
     * maximum number of cores per server
     * @type {number}
     * @memberof ResourceLimits
     */
    coresPerServer: number;
    /**
     * maximum cores per contract
     * @type {number}
     * @memberof ResourceLimits
     */
    coresPerContract: number;
    /**
     * number of cores provisioned
     * @type {number}
     * @memberof ResourceLimits
     */
    coresProvisioned: number;
    /**
     * maximum ram per server
     * @type {number}
     * @memberof ResourceLimits
     */
    ramPerServer: number;
    /**
     * maximum ram per contract
     * @type {number}
     * @memberof ResourceLimits
     */
    ramPerContract: number;
    /**
     * ram provisioned
     * @type {number}
     * @memberof ResourceLimits
     */
    ramProvisioned: number;
    /**
     * hdd limit per volume
     * @type {number}
     * @memberof ResourceLimits
     */
    hddLimitPerVolume: number;
    /**
     * hdd limit per contract
     * @type {number}
     * @memberof ResourceLimits
     */
    hddLimitPerContract: number;
    /**
     * hdd volume provisioned
     * @type {number}
     * @memberof ResourceLimits
     */
    hddVolumeProvisioned: number;
    /**
     * ssd limit per volume
     * @type {number}
     * @memberof ResourceLimits
     */
    ssdLimitPerVolume: number;
    /**
     * ssd limit per contract
     * @type {number}
     * @memberof ResourceLimits
     */
    ssdLimitPerContract: number;
    /**
     * ssd volume provisioned
     * @type {number}
     * @memberof ResourceLimits
     */
    ssdVolumeProvisioned: number;
    /**
     * DAS (Direct Attached Storage) volume provisioned
     * @type {number}
     * @memberof ResourceLimits
     */
    dasVolumeProvisioned: number;
    /**
     * total reservable ip limit of the customer
     * @type {number}
     * @memberof ResourceLimits
     */
    reservableIps: number;
    /**
     * reserved ips on a contract
     * @type {number}
     * @memberof ResourceLimits
     */
    reservedIpsOnContract: number;
    /**
     * reserved ips in use
     * @type {number}
     * @memberof ResourceLimits
     */
    reservedIpsInUse: number;
    /**
     * k8s clusters total limit
     * @type {number}
     * @memberof ResourceLimits
     */
    k8sClusterLimitTotal: number;
    /**
     * k8s clusters provisioned
     * @type {number}
     * @memberof ResourceLimits
     */
    k8sClustersProvisioned: number;
    /**
     * NLB total limit
     * @type {number}
     * @memberof ResourceLimits
     */
    nlbLimitTotal: number;
    /**
     * NLBs provisioned
     * @type {number}
     * @memberof ResourceLimits
     */
    nlbProvisioned: number;
    /**
     * NAT gateway total limit
     * @type {number}
     * @memberof ResourceLimits
     */
    natGatewayLimitTotal: number;
    /**
     * NAT gateways provisioned
     * @type {number}
     * @memberof ResourceLimits
     */
    natGatewayProvisioned: number;
}


